### ISSUE TITLE
Conflicting ID 'configure'

### ISSUE THREAD

**Issue by DiogoMarques29** [saltstack-formulas/wordpress-formula#14]
Hi,
I'm having problems when using multiple sites:
`Rendering SLS 'base:wordpress.config' failed: Conflicting ID 'configure'`

```
wordpress:
  cli:
    source: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    hash:  https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar.sha512
  sites:
    site.A:
      username: userA
      password: passA
      database: siteA
      dbhost: localhost
      dbuser: wordpress
      dbpass: 'passA'
      url: http://site.A
      title: 'Site A'
      email: emailA@gmail.com
    site.B:
      username: userB
      password: passB
      database: siteB
      dbhost: localhost
      dbuser: wordpress
      dbpass: 'passB'
      url: http://site.B
      title: 'Site B'
      email: emailB@gmail.com
  lookup:
    docroot: /var/www/wordpress
```
