### ISSUE TITLE
commmand wp turns with no output

### ISSUE THREAD

**Issue by obicho** [saltstack-formulas/wordpress-formula#19]
After installing the formula, I can't find the WP installation anywhere.
When I try to run

> /usr/local/bin/wp

It simply returns without no output

I can't quote figure out what the error is.

I did get the message that install was successful

Summary for mini15
-------------
Succeeded: 11 (changed=7)
Failed:     0
-------------
Total states run:     11
Total run time:   28.907 s

**Comment by russellballestrini** [comment]
Ok first of all, this is a defect in the documentation. The Readme does not show that you need the following, in your pillar:

```
wordpress:
  cli:
    source: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    hash: 2906a669a28d2a344da88c63c96aff3c
```

Once you correct this issue, the `cmd.run` states will fail because the wordpress CLI should run as the webserver user, not root.

This is due to SaltStack removing `user` in favor of `runas`.

Reference: https://docs.saltstack.com/en/2017.7/ref/states/all/salt.states.cmd.html#salt.states.cmd.run
